library = {}


def add_book(title, author):
    pass



def remove_book(title):
    pass



def search_book(title):
    pass



def list_books():
    pass



def main():
    while True:
        print("\nWelcome to the Library Management System")
        print("1. Add a book")
        print("2. Remove a book")
        print("3. Search for a book")
        print("4. List all books")
        print("5. Exit")
        choice = input("What would you like to do? Please enter a choice 1-5: ")

        if choice == '1':
            title = input("Please enter a book title: ")
            author = input("Please enter the author of the book: ")
            add_book(title, author)
        elif choice == '2':
            title = input("Please enter the title of the book to remove: ")
            remove_book(title)
        elif choice == '3':
            title = input("Please enter the title of the book you would like to search for: ")
            search_book(title)
        elif choice == '4':
            list_books()
        elif choice == '5':
            print("End of the program.")
            break
        else:
            print("Please choose from the options provided.")



if __name__ == "__main__":
    main()
